language: node_js
node_js:
  - "6.1"
  - "5.11"
  - "4.3"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
    - npm install -g gulp
    - npm test
